import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";

async function fetcher<JSON = any>(
  input: RequestInfo,
  init?: RequestInit
): Promise<JSON> {
  const res = await fetch(input, init);
  return res.json();
}

const Home: NextPage = () => {
  const { data } = useSWR("/api/hello", fetcher);

  return (
    <div>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout">
        <h3 className="font-medium mb-8">Codeforces final standings</h3>
        <div className="w-full grid grid-cols-12 mb-5 text-center">
          <div className="font-bold border px-1 py-1 text-left">#</div>
          <div className="col-span-4 text-left font-bold border px-1 py-1">
            who
          </div>
          <div className="font-bold border px-1 py-1">=</div>
          <div className="font-bold border px-1 py-1">penalty</div>
          <div className="font-bold border px-1 py-1">a</div>
          <div className="font-bold border px-1 py-1">b</div>
          <div className="font-bold border px-1 py-1">c</div>
          <div className="font-bold border px-1 py-1">d</div>
          <div className="font-bold border px-1 py-1">e</div>
        </div>
        <div className="w-full">
          {
            // @ts-ignore
            data?.data.map((d, i) => (
              <div className="grid grid-cols-12 text-center" key={i}>
                <div className="text-left border px-1">{d?.["#"]}</div>
                <div className="col-span-4 text-left border px-1">{d?.who}</div>
                <div className="border px-1">{d?.["="]}</div>
                <div className="border px-1">{d?.penalty}</div>
                <div className="border px-1">{d?.a}</div>
                <div className="border px-1">{d?.b}</div>
                <div className="border px-1">{d?.c}</div>
                <div className="border px-1">{d?.d}</div>
                <div className="border px-1">{d?.e}</div>
              </div>
            ))
          }
        </div>
      </div>
    </div>
  );
};

export default Home;
